@ECHO OFF

ECHO CHECKING FOR A DOWNLOADED EDI FILE.....

IF NOT EXIST C:\PROEDIW\EDIIN\UA0000.000 GOTO END

ECHO CLEANING UP OLD FILES NOW

IF EXIST C:\PROEDIW\FLATIN\IN830.EDI DEL C:\PROEDIW\FLATIN\IN830.EDI >NUL

IF EXIST C:\PROEDIW\FLATIN\IN850.EDI DEL C:\PROEDIW\FLATIN\IN850.EDI >NUL

IF EXIST C:\PROEDIW\FLATIN\IN862.EDI DEL C:\PROEDIW\FLATIN\IN862.EDI >NUL

ECHO TRANSLATING THE RAW EDI FILE.

CD C:\PROEDIW

AUDITW 3,UA0000.000,MIPC

:end

exit